<a href="https://colab.research.google.com/github/poepoe3060/Numpy/blob/main/numpy_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Import

In [ ]:
import numpy as np
import sys


###Broadcasting and Vectorized operations

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
a + 10

array([10, 11, 12, 13])

In [ ]:
a * 10

array([ 0, 10, 20, 30])

In [ ]:
a += 100

In [ ]:
a

array([100, 101, 102, 103])

In [ ]:
l = [0, 1, 2, 3]

In [ ]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
b = np.array([10, 10, 10, 10])

In [ ]:
a + b

array([10, 11, 12, 13])

In [ ]:
a * b

array([ 0, 10, 20, 30])

In [ ]:
a = np.arange(5)

In [ ]:
a + 20

array([20, 21, 22, 23, 24])

In [ ]:
a = np.arange(5)

In [ ]:
print( a <=3 )

[ True  True  True  True False]


###Numpy Arrays

In [ ]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([1, 2, 3, 4, 5])

In [ ]:
b = np.array([0, 0.5, 1, 1.5, 2])

In [ ]:
a[0], a[1]

(np.int64(1), np.int64(2))

In [ ]:
a[0:]

array([1, 2, 3, 4, 5])

In [ ]:
a[1:3]

array([2, 3])

In [ ]:
a[1:5]

array([2, 3, 4, 5])

In [ ]:
a[1:-1]

array([2, 3, 4])

In [ ]:
b.dtype

dtype('float64')

In [ ]:
c = np.array(['a', 'b' , 'c'])

In [ ]:
c.dtype

dtype('<U1')

In [ ]:
d = np.array([{'a': 1}, sys])

In [ ]:
d.dtype

dtype('O')

In [ ]:
p = np.array([1,3,5], dtype='int32')
q = np.array([1,2,3])
p * q

array([ 1,  6, 15])

In [ ]:
h = np.array([[1.0, 2.0, 3.0], [3.0, 4.0, 5.0]])

In [ ]:
print(h)

[[1. 2. 3.]
 [3. 4. 5.]]


In [ ]:
# Get Dimension
p.ndim

1

In [ ]:
p.shape

(3,)

In [ ]:
# Get Shaoe
h.shape

(2, 3)

In [ ]:
# Get Type
h.dtype

dtype('float64')

In [ ]:
# Get Size
p.itemsize

4

In [ ]:
# Get total size
p.size * p.itemsize

12

In [ ]:
a = np.array([[1, 2, 3, 4, 5], [6,7,8,9,10]])

In [ ]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
a[:, 3] = 20
print(a)

[[ 1  2  3 20  5]
 [ 6  7  8 20 10]]


In [ ]:
a[:, 2] = 20
print(a)

[[ 1  2 20 20  5]
 [ 6  7 20 20 10]]


In [ ]:
a[1, 2] = 20
print(a)

[[ 1  2 20 20  5]
 [ 6  7 20 20 10]]


In [ ]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(np.full_like(a, 100))

[[100 100 100 100 100]
 [100 100 100 100 100]]


In [ ]:
output = np.zeros((7, 7))
z = np.ones((5, 5))
z[2, 2] = 5
output[1:-1, 1:-1] = z

In [ ]:
output

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 5., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
a = np.ones((5, 5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
z[1,1] = 2
z

array([[0., 0., 0.],
       [0., 2., 0.],
       [0., 0., 0.]])

In [ ]:
a[3,3] = 7
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 7., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
a[:3, :2]

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Copying arrays

In [ ]:
c = np.array([1, 2, 3])
d = c.copy()
d[0] = 100
print(d)

[100   2   3]


In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = a
b[2] =20
b

array([ 1,  2, 20,  4,  5])

### Mathematics

In [ ]:
a = np.array([1, 2, 3, 4, 5])

print(a)

[1 2 3 4 5]


In [ ]:
a + 2

array([3, 4, 5, 6, 7])

In [ ]:
a - 3

array([-2, -1,  0,  1,  2])

In [ ]:
a * 5

array([ 5, 10, 15, 20, 25])

In [ ]:
a / 4

array([0.25, 0.5 , 0.75, 1.  , 1.25])

In [ ]:
b = np.array([1, 0, 1, 0, 1])
a + b

array([2, 2, 4, 4, 6])

In [ ]:
a ** 2

array([ 1,  4,  9, 16, 25])

In [ ]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [ ]:
# Take the cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

### Linear Algebra

In [ ]:
 x = np.ones((2, 3))
 print(x)

 y = np.full((3, 2), 2)
 print(y)

 np.matmul(x, y)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
# Find a determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

### Statistics

In [ ]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)


np.int64(1)

In [ ]:
np.min(stats, axis=0)

array([1, 2, 3])

In [ ]:
np.max(stats)

np.int64(6)

In [ ]:
np.max(stats, 1)

array([3, 6])

In [ ]:
np.sum(stats)

np.int64(21)

In [ ]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [ ]:
v = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
y = np.max(v, axis=1).sum()
y

np.int64(15)

### Reorganizing Arrays

In [ ]:
before = np.array([[1 ,2 ,3 ,4], [5, 6, 7, 8]])
print(before)

after = before.reshape((4 ,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal Stack
h1 = np.ones([2, 4])
h2 = np.zeros([2, 2])

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [ ]:
a = np.ones((2, 4))
b = a.reshape((4, 2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
a = np.ones((2, 4))
b = a.reshape((2, 4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
a = np.ones((2, 4))
b = a.reshape((8, 1))
print(b)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


### Miscellaneous

In [ ]:
# Load Data from file
filedata = np.genfromtxt('data.txt')
filedata.astype('int32')
filedata

array([ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  55.,
        66.,  77.,  88.,  99.,  33.,  44.,  22.,  77.,  61.,  72.,  83.,
        94., 123., 222., 345., 678., 999., 321., 654., 761.])

In [ ]:
# Boolean masking and advanced indexing
filedata > 50


array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [ ]:
filedata[filedata > 50]

array([ 55.,  66.,  77.,  88.,  99.,  77.,  61.,  72.,  83.,  94., 123.,
       222., 345., 678., 999., 321., 654., 761.])

In [ ]:
np.any(filedata > 50, axis=0)

np.True_

In [ ]:
np.all(filedata > 50, axis=0)

np.False_

In [ ]:
# we can index with a list in Numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [ ]:
(~((filedata > 50) & (filedata < 100)))

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False,  True,  True,  True,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True])